version: "2"
services:
  nats:
    image: appcelerator/nats-streaming
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4223:4222"
      - "8223:8222"

  sut:
    image: appcelerator/sut
    build:
      context: ./sut
      dockerfile: Dockerfile
    depends_on:
      - nats
